#
# Travis CI configuration file for the IPP sample project.
#
# Copyright © 2018 by the IEEE-ISTO Printer Working Group.
#
# Licensed under Apache License v2.0.  See the file "LICENSE" for more
# information.
#

language: c

matrix:
  include:
    # Linux-specific build stuff
    - os: linux
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y avahi-daemon avahi-utils cura-engine libavahi-client-dev libfreetype6-dev libgnutls28-dev libharfbuzz-dev libjbig2dec0-dev libjpeg-dev libmupdf-dev libnss-mdns libopenjp2-7-dev libpng-dev zlib1g-dev

    # macOS-specific build stuff
    - os: osx
      osx_image: xcode9.4
