
name: ipp
version: 1.0
summary: IPP Sample Implementation
description: |
  The ippsample project provides sample implementations of an IPP Client, Proxy,
  Server, and other tools. It is based on the CUPS source code and is maintained
  by the PWG IPP workgroup.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: server/printer.png

apps:
    server:
        command: usr/bin/server
        plugs: [avahi-observe home network network-bind]
    find:
        command: usr/bin/find
        plugs: [avahi-observe home network]
    tool:
        command: usr/bin/tool
        plugs: [avahi-observe home network]
    transform:
        command: usr/bin/transform
        plugs: [home network]
    transform3d:
        command: usr/bin/transform3d
        plugs: [home network]

parts:
    main:
        plugin: autotools
        source: .

build-packages: [libavahi-dev libgnutls-dev libjpeg-dev libmupdf-dev libpng-dev zlib-dev]

